config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get 'sign_in', to: 'devise/sessions#new'
  end

  root to: 'events#index'

  resources :events, only: [:index, :show] do
    member do
      resources :bookings, only: [:new, :create] do
        collection do
          post :cancel
        end
      end
    end
  end
end

app/models/actor.rb
class Actor < ApplicationRecord
  belongs_to :user
  belongs_to :event

  scope :for_event, -> (event_id) { where(event_id: event_id) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  extend Enumerize

  enumerize :status, in: [:new, :confirmed, :cancelled], default: :new, scope: true
  belongs_to :event
  belongs_to :participant, foreign_key: :actor_id

  validates :status, presence: true

  def cancel!
    update!(status: :cancelled)
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true
  validates :event_start_time, presence: true
  validates :event_end_time, presence: true

  has_many :bookings
  has_many :participants, through: :bookings

  scope :newest, -> { order(:created_at) }

  def past_event?
    Time.now >= event_end_time
  end
end

app/models/participant.rb
class Participant < Actor
  acts_as_paranoid

  has_one :booking, foreign_key: :actor_id

  def cancel!
    self.destroy
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  extend Enumerize

  enumerize :status, in: [:created, :paid], default: :created
  belongs_to :booking

  validates :amount, presence: true
  validates :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize

  enumerize :gender, in: [:male, :female]
  devise :database_authenticatable, :registerable, :validatable

  has_many :participations, class_name: 'Actor'

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from ActiveRecord::RecordNotFound do
    render file: 'public/404', status: 404
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_event
  before_action :initialize_booking, only: [:new]

  def new;end

  def create
    booking_service = Bookings::EventBookingForm.new(@event, current_user, booking_params)
    booking_service.save

    redirect_to event_path(@event)
  end

  def cancel
    cancellation_service = Bookings::CancellationForm.new(@event, current_user)
    cancellation_service.save

    redirect_to event_path(@event)
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def initialize_booking
    @booking_calulator = Bookings::PriceCalculator.new(@event, current_user)
    @booking = @event.bookings.new(amount: @booking_calulator.calculate)
  end

  def booking_params
    params.require(:booking).permit(:amount)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_events, only: [:index]
  before_action :set_event, only: [:show]

  def index;end

  def show
    @participants = Events::Participants::FindService.new(@event).find
    @participants.includes(:user)
  end

  private

  def set_events
    @events = Event.newest
  end

  def set_event
    @event = Event.find params[:id]
  end
end

app/views/bookings/new.html.slim
.container
  h2 Book Event Ticket For Individual

  = form_for(@booking, url: bookings_path, method: :post) do |f|
    .field
      = f.label 'Event Price'
      br
      = @event.price

    - if @booking_calulator.discount
      .field
        = f.label 'Discount'
        br
        = @booking_calulator.discount

    .field
      = f.label :amount, 'Total'
      br
      = f.number_field :amount, readonly: true

    br
    .actions
      = f.submit 'Book'
  <br>

app/views/events/index.html.slim
.container
  .panel.panel-default
    .panel-heading Events
    table.table
      - if @events.present?
        thead
          tr
            th Event Title
            th Event Start Time
            th Event End Time
            th Created At
        tbody
            - @events.each do |event|
              tr
                td = link_to event.title, event_path(event)
                td = event.event_start_time.strftime("%a, %d %B %Y %I %p")
                td = event.event_end_time.strftime("%a, %d %B %Y %I %p")
                td = event.created_at.strftime("%a, %d %B %Y")
      - else
        h2 No Events

app/views/events/show.html.slim
.container
  .panel.panel-default
    .panel-heading Event Participant of #{@event.title}
    - is_current_user_participant = false
    table.table
      - if @participants.present?
        thead
          tr
            th Name
            th Gender
        tbody
            - @participants.each do |participant|
              - user = participant.user
              - next if user_signed_in? && user.id == current_user.id && is_current_user_participant = true
              tr
                td = user.name
                td = user.gender
      - else
        h2 No Participant

  - if user_signed_in? && !@event.past_event?
    .panel.panel-default
      .panel-heading Your Action
      - if is_current_user_participant
        strong = link_to 'Unattend', cancel_bookings_path(@event), method: :post
      - else
        strong = link_to 'Attend', new_booking_path(@event)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BukukasEventBooking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <ul class="nav nav-pills">
        <li role="presentation" class="active">
          <%= link_to 'Home', root_path %>
        </li>
        <% if user_signed_in? %>
          <li role="presentation"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li role="presentation">
            <%= link_to 'Login', new_user_session_path %>
          </li>
          <li role="presentation">
            <%= link_to 'Register', new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>